### ISSUE TITLE
plug in not responding

### ISSUE THREAD

**Issue by drone07** [latenitefilms/BRAWToolbox#95] opened 2023-03-08 19:14 UTC
One day after installing BRAW toolbox I get this message: "A plug-in is not responding The plug in brawPlugIn is not responding. This plug in will be disabled." Mac OS 12.6., Final Cut Pro 10.6.5. Relaunching and restarting Mac did not solve the problem. Problem occurred when I applied "BRAW toolbox" from the installed effects on to a BRAW file.  Any help?

**Comment by latenitefilms** [comment] 2023-03-08 19:19
That's strange. Are you able to send me your log files and crash logs?

See: https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files

**Comment by drone07** [comment] 2023-03-08 19:30
[Application Support.zip](https://github.com/latenitefilms/BRAWToolbox/files/10924387/Application.Support.zip)

**Comment by drone07** [comment] 2023-03-09 15:58
Hi again, I just wanted to add: the problem still persists, I can import BRAWs (although I get the spinning wheel from time to time and have to force quit toolbox and final cut) and I can play the BRAW files in final cut. When I want to apply the "effect" toolbox, suddenly it says "no BRAW file selected" and I can no longer play the just imported file. 
This is just another observation: today I had troubles opening Resolume (the VJ - software). Finally it worked and I can work with the program without any other problems. Could there be a connection? But anyway: I could use BRAW toolbox for a couple of days until yesterday and I have Resolume Arena installed for a long time…

**Comment by latenitefilms** [comment] 2023-03-09 19:23
You should never have to manually apply the BRAW Toolbox video effect. This is applied by the Workflow Extension. If you want to manipulate the RAW metadata you need to double click (or "Open Clip") the Synchronised Clip, and you'll find the BRAW Toolbox effect applied to a Generator inside.

If you're adding the BRAW Toolbox video effect manually to an existing BRAW Toolbox Synchronised Clip, then it's expected that you'll see no BRAW file loaded, as the BRAW Toolbox video effect is essentially our "renderer". If you then manually load a BRAW file in the Inspector, that clip is essentially loading the same BRAW file twice.

You can learn more about how things work here:

https://brawtoolbox.io/faq/#how-does-it-work

I will have a proper look at the files you uploaded today, however it looks like maybe you only uploaded the log files, but no crash reports? If you can also provide those as well that would be great. Where to find them is explained here:

https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files

What kind of system are you working on? Have you confirmed your GPU and drives are fast enough? See:

https://brawtoolbox.io/troubleshooting/#is-my-mac-fast-enough-to-play-braw-files

Two other general pieces of advice - I recommend ticking the "Create Multicam Clips" option, as Multicam Clips generally work better in FCPX, and also grant sandbox access to the drive that contains the footage for a very minor performance improvement. See:

https://brawtoolbox.io/faq/#i-dont-like-synchronised-clips-can-i-import-a-multicam-clips-instead

https://brawtoolbox.io/collaboration/

I'll reply again in a few hours when I'm back in the office and have reviewed your log files. Thanks!

**Comment by drone07** [comment] 2023-03-09 20:12
Thank you for your reply, that totally makes sense. So I should not touch the "effects" in the "BRAW toolbox" section at all, right?
I´ve missed the crash report files - here they are!
And yes, I´ve run the Blackmagic speed test. I'm working on a Macbook 16´´, OS 12:6, 64GM memory.
Thank you for your suggestions!

[crash reports.zip](https://github.com/latenitefilms/BRAWToolbox/files/10935639/crash.reports.zip)

**Comment by latenitefilms** [comment] 2023-03-10 00:39
Correct, you shouldn't ever need to manually apply these effects to clips:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/22286696/224192712-36d9489f-59a5-4e47-8ec0-480452a03ad9.png">

All of the above are automatically applied by the BRAW Toolbox Workflow Extension when you import BRAW Clips.

Again, if you need to manipulate the RAW metadata of a clip, you should "go inside" the Synchronised Clip to access the BRAW Toolbox video effect.

One thing I did notice in your log files is that there is a random macOS sandboxing issue. It doesn't really give any clues as it why it happened, and restarting your computer would have probably fixed it. However, as explained above, if you "Grant Sandbox Access" to the drive that contains all your BRAW files, that would prevent this particular issue:

https://brawtoolbox.io/collaboration/

I've also had a look at your crash reports. Unfortunately I'm not really sure yet why it's crashing for your in this circumstance, as there's no obvious clues as to what's going wrong. However I'll keep digging and see what I can come up with.

Fingers and toes crossed though, that using Multicam Clips and Granting Sandbox Access will help make things more stable.

I'm going to close this issue for now, but feel free to re-open if you're still having issues or crashes.

**Closed by latenitefilms** 2023-03-10 00:39 UTC
Labels: tech support
