### ISSUE TITLE
Parameters unavailable without Metadata Reset

### ISSUE THREAD

**Issue by t3dc** [latenitefilms/BRAWToolbox#177] opened 2024-05-29 10:59 UTC
This problem pops up on clips sometimes and I'm not sure why. One clip in the timeline will be fine, but when I open the one right next to it, I can't actually access any of the metadata settings:

![Screenshot 2024-05-29 at 11 50 10 AM](https://github.com/latenitefilms/BRAWToolbox/assets/52919338/7aa84b19-1a6e-4f20-92e1-cdff1273f04e)

As you can see, the window truncates after "Reset Metadata." As near as I can determine, there is no way to scroll stretch or adjust the window to regain access. However, if I click "Reset Metadata" the problem is magically resolved:

![Screenshot 2024-05-29 at 11 50 20 AM](https://github.com/latenitefilms/BRAWToolbox/assets/52919338/7efed53d-1cd9-46e0-a766-31c700600b02)

While generally speaking the metadata isn't that important, I do often tweak ISOs and such and it's frustrating to have to throw it all away so that I can access the LUT setting for example.

Thanks!

**Comment by latenitefilms** [comment] 2024-05-29 14:36
That's very odd! However it looks like a Final Cut Pro User Interface Bug, rather than anything specific to BRAW Toolbox, especially considering that yellow outline. Have you tried making the Inspector full height (ie double click the top of the Inspector) or tried changing your Window Layout?

Clicking "Reset Metadata" definitely shouldn't be necessary in this case - for whatever reason, Final Cut Pro isn't showing the full Inspector. What happens if you click the "Hide" button for BRAW Toolbox and show it again?

I'll report this to Apple too and see if they have any ideas.

**Comment by t3dc** [comment] 2024-05-29 14:48
Hi Chris. Yeah, it’s odd. doesn’t happen on every clip. Changing the window arrangement doesn’t matter. Nor does show/hide. Of course l, expanding the pane expands the entire pane, but doesn’t make the braw window any larger. Yellow outline is just a highlight because I clicked on it.

**Comment by latenitefilms** [comment] 2024-05-29 20:51
What I mean with the yellow outline is that there's no yellow line on the bottom in that first screenshot, so something funky is clearly going wrong in Final Cut Pro. Have you tried trashing your Final Cut Pro preferences?

**Comment by t3dc** [comment] 2024-05-31 11:36
I haven’t, though I’ve tracked this issue across three different Macs, so… I think it’s not preference related.

**Comment by latenitefilms** [comment] 2024-05-31 22:54
Very strange. I haven't been able to reproduce this on any of our machines, and as far as I'm aware, no one else has reported this problem so far.

We have a test library of 83 different varieties of BRAW clips, and all of these seem to work as intended.

What version of Final Cut Pro are you running? What version of macOS?

What are the specifications of the BRAW file you're working with?

Is there a common denominator between the clips that don't show the metadata and those that do?

Are you able to send us your log files? Maybe there's a clue in there.

See: https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files

Is it possible to create a test library that demonstrates this issue (i.e. can you drag one of the "broken" clips into a new library and send it to us, along with the original BRAW file)?

**Comment by latenitefilms** [comment] 2024-09-09 03:55
Closing this issue for now, feel free to re-open if you're still having issues.

**Closed by latenitefilms** 2024-09-09 03:55 UTC
Labels: tech support
