### ISSUE TITLE
Off Speed and Remove Selected

### ISSUE THREAD

**Issue by StevePlitt** [latenitefilms/BRAWToolbox#91] opened 2023-02-27 05:12 UTC
The first one I noticed when importing footage. When I click on "Remove Selected" the plugin needs to be restarted. When it comes back, all the clips have been removed.

The second is when using off-speed footage in the timeline. We shot some 48fps footage to play back at 24, and it re-edits itself and can't be slipped back into the proper position. We shot it correctly, using Off Speed mode on the camera. It plays back at the correct speed in the bin, and even the timeline, but the in and out points change and cant be fixed.

**Comment by latenitefilms** [comment] 2023-02-27 05:21
> The first one I noticed when importing footage. When I click on "Remove Selected" the plugin needs to be restarted.

That's strange - "Remove Selected" all seems to be working fine here. Are you using the latest v1.0.4 release?

Are you able to do a screen recording demonstrating what's happening?

> When it comes back, all the clips have been removed.

This is normal expected behaviour - everything is reset when you close the Workflow Extension.

> The second is when using off-speed footage in the timeline. We shot some 48fps footage to play back at 24, and it re-edits itself and can't be slipped back into the proper position. We shot it correctly, using Off Speed mode on the camera. It plays back at the correct speed in the bin, and even the timeline, but the in and out points change and cant be fixed.

I don't quite understand. A screen recording to demonstrate might be best way to explain?

We have had some other users report issues with off-speed clips, but have never been able to reproduce yet.

Are you saying it looks correct in the browser, but as soon as you put into the timeline it does strange things?

Can you try creating Multicam Clips instead of Synchronised Clips?

See: https://brawtoolbox.io/faq/#i-dont-like-synchronised-clips-can-i-import-a-multicam-clips-instead

**Comment by latenitefilms** [comment] 2023-04-04 07:23
I haven't had any further response, so I'm going to close this issue for now. Feel free to re-open if you still need help!

**Closed by latenitefilms** 2023-04-04 07:23 UTC
Labels: tech support, waiting on reply
