### ISSUE TITLE
The Effect ID is Invalid - FxPlug4 not installing correctly

### ISSUE THREAD

**Issue by CodyCarlson22** [latenitefilms/BRAWToolbox#85] opened 2023-02-16 03:25 UTC
When I drag the event into the desired library all the clips appear in the media browser with a black thumbnail. I cannot play them back in the media browser and when I try to drag them into a timeline the clips appear as a black screen during playback, but I can hear the audio playing from the clip. I have gone through all of the trouble shooting steps and would really appreciate help with this.

I am using a M1 Ultra Mac Studio running Monteray OS.

**Comment by latenitefilms** [comment] 2023-02-16 03:37
Try completely uninstalling BRAW Toolbox using [this tool](https://brawtoolbox.io/uninstall/), and reinstall from the Mac App Store, making sure you carefully following the [instructions](https://brawtoolbox.io/installation/) here. Let me know if that helps!

**Comment by latenitefilms** [comment] 2023-02-16 03:41
_(Duplicate of #55, #64, #77)_

**Comment by CodyCarlson22** [comment] 2023-02-16 16:01
Thank you so much! I really appreciate your quick response. After deleting BRAW Toolbox and re-downloading the issue has been solved. 

Although, once I try and import my XML from FCPX to Davinci Resolve, the clips once again show up as black in Davinci Resolve. Am I unable to send XMLs to Davinci resolve when using this software?

**Closed** 2023-02-16 19:07 UTC
Labels: duplicate, tech support
