### ISSUE TITLE
[Panasonic S1H] Workflow Extension fails if BRAW clip doesn't have valid timecode

### ISSUE THREAD

**Issue by shotbywsh** [latenitefilms/BRAWToolbox#70] opened 2023-02-05 04:11 UTC
hey i just bought braw tooldbox because i have braw footage i need to bring into final cut pro. when i open the brawtoolbox and import footage a big grey box appears and nothing loads up. please help me.
<img width="2048" alt="Screenshot 2023-02-04 at 11 11 23 PM" src="https://user-images.githubusercontent.com/124481504/216801073-ae21afa8-852a-4eb7-9239-096119f4890f.png">
  i have attatched a image on what happens after i click the files i wanted imported.

**Comment by latenitefilms** [comment] 2023-02-05 04:54
Well, that's strange - I've never seen that before!

So this appears after you press the **Import BRAW Files** button, select some files then try to load them?

What version of macOS and Final Cut Pro?

Are you able to share a screen recording of what happens?

Are you able to share the log files from BRAW Toolbox as explained [here](https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files)?

**Comment by shotbywsh** [comment] 2023-02-05 05:45
https://user-images.githubusercontent.com/124481504/216803861-1a2637ef-9bb7-4e77-a7bd-80f7ea0161e4.mov

**Comment by shotbywsh** [comment] 2023-02-05 05:46
it just stays at this screen

**Comment by shotbywsh** [comment] 2023-02-05 05:47
is there anyway you can call me?

**Comment by latenitefilms** [comment] 2023-02-05 06:10
That's really strange. The only thing I think it could be is some strange bug that's causing an empty Relink window to appear, although I can't see how, and I can't reproduce on my MacBook Pro running Monterey. Weird!

Can you try changing the bottom Toolbox dropdown to **Convert PROJECT to Resolve Friendly FCPXML**, restart FCPX, and see if that makes any difference?

Did it ever work, or have you always had this issue?

Are you able to share your log files?

https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files

Shoot me an email if you want to jump on Zoom or TeamViewer:

https://brawtoolbox.io/support/

**Comment by shotbywsh** [comment] 2023-02-05 06:23
i just bought the app today never used it. did what u said still not working and when i drag and drop the files into i get this message

https://user-images.githubusercontent.com/124481504/216804984-ea31c221-79f9-4060-9fed-9e4024b51457.mov

**Comment by shotbywsh** [comment] 2023-02-05 06:29
how can i uninstall and reinstall and see if that works?

**Comment by latenitefilms** [comment] 2023-02-05 06:32
Very strange! Shoot me through an email with your log files as per above link, and we can also jump on a screen sharing session.

Uninstall instructions here:

https://brawtoolbox.io/uninstall/

**Comment by shotbywsh** [comment] 2023-02-05 07:01
<img width="295" alt="Screenshot 2023-02-05 at 2 00 59 AM" src="https://user-images.githubusercontent.com/124481504/216806105-29597eb8-92ce-470c-87fd-192768138587.png">
when i try to uninstall and open the zip i get this

**Comment by shotbywsh** [comment] 2023-02-05 07:05
<img width="489" alt="Screenshot 2023-02-05 at 2 04 54 AM" src="https://user-images.githubusercontent.com/124481504/216806273-626893d5-a149-44c7-9a01-f926998f709b.png">
i get this message when i click uninstall

**Comment by shotbywsh** [comment] 2023-02-05 07:10
just emailed you , if u dont get it can u please email me back @ wallstreethippies@gmail.com i have a project due in a week and i need this solved! thank you so much

**Comment by latenitefilms** [comment] 2023-02-05 07:11
Ah, right, sorry, I forgot that the uninstall tool currently has issues on macOS Ventura due to new security settings (as discussed in #42). This will be fixed in the future.

I've just replied to your email.

**Comment by latenitefilms** [comment] 2023-02-05 23:18
This will be fixed in v1.0.1.

**Closed by latenitefilms** 2023-02-05 23:18 UTC
Labels: bug
